(package "vs-revbuf"
         "0.1.1"
         "Revert buffers like Visual Studio")

(website-url "https://github.com/emacs-vs/vs-revbuf")
(keywords "convenience" "revert" "vs")

(package-file "vs-revbuf.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "fextern")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
